- name: DBT run
        run: |
          mkdir -p ~/.dbt
          cp dbt/sales_project/profiles.yml ~/.dbt/profiles.yml
          cd dbt/sales_project
          dbt run

      - name: DBT test
        run: |
          cd dbt/sales_project
          dbt test